CREATE TABLE `b_sales_history` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `COUNTRY` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `UID` bigint(20) DEFAULT NULL,
  `QUOTETOTAL` int(11) DEFAULT NULL,
  `SPECHANDLING` int(11) DEFAULT NULL,
  `PROMOCOUPONAMT` int(11) DEFAULT NULL,
  `STATUS` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `DELADDID` bigint(20) DEFAULT NULL,
  `NOTES` varchar(1024) COLLATE utf8mb4_bin DEFAULT NULL,
  `DISCPER` int(11) DEFAULT NULL,
  `DISCPASSED` int(11) DEFAULT NULL,
  `DISCREASON` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `CREATED` datetime DEFAULT NULL,
  `UPDATED` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Uid_Index` (`UID`) USING BTREE,
  KEY `Created_Index` (`CREATED`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Master Sales Entity';

CREATE TABLE `cart_items` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `SID` bigint(20) DEFAULT NULL,
  `BID` bigint(20) DEFAULT NULL,
  `QTY` int(11) DEFAULT NULL,
  `LISTPRICE` int(11) DEFAULT NULL,
  `SELLPRICE` int(11) DEFAULT NULL,
  `DISCREASON` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `Sales_Index` (`SID`) USING BTREE,
  KEY `Book_Index` (`BID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Sales items';

CREATE TABLE `book_master` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AUTHORFIRSTNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AUTHORLASTNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SKU` varchar(50) COLLATE utf8mb4_bin DEFAULT '0',
  `BARCODE` varchar(50) COLLATE utf8mb4_bin DEFAULT '0',
  `STOCKCODE` varchar(50) COLLATE utf8mb4_bin DEFAULT '0',
  `CREATED` datetime DEFAULT NULL,
  `UPDATED` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATEDBY` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `DELETED` datetime DEFAULT NULL,
  `SPOINT` mediumtext COLLATE utf8mb4_bin,
  `ACTIVE` tinyint(4) DEFAULT 0,
  `PUBLIC` tinyint(4) DEFAULT '0',
  `COSTPRICEINC` int(11) DEFAULT '0',
  `LISTPRICEINC` int(11) DEFAULT '0',
  `FRIENDLYURL` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NAME_INDEX` (`NAME`) USING BTREE,
  KEY `FRIENDLYURL_INDEX` (`FRIENDLYURL`) USING BTREE,
  KEY `AUTHORFIRSTNAME_INDEX` (`AUTHORFIRSTNAME`) USING BTREE,
  KEY `AUTHORLASTNAME_INDEX` (`AUTHORLASTNAME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='The BOOK master table.';
